[package]
name = "crc32sum"
version = "0.1.0"
edition = "2021"
licence = "MIT"
description = "calculate crc32 checksum of files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
